#!/usr/bin/env bash
# Script that displays all active IPv4 IPs on the machine

# Use ifconfig to get network interfaces and extract IPv4 addresses
ifconfig | grep -oE 'inet ([0-9]{1,3}\.){3}[0-9]{1,3}' | cut -d' ' -f2
