#!/usr/bin/env bash
# Script that displays all active IPv4 IPs on the machine

# Use ifconfig to get network interfaces and extract IPv4 addresses
ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*'
